[run]
  deadline = "5m"
  skip-files = []

[linters-settings]

  [linters-settings.govet]
    check-shadowing = true

  [linters-settings.gocyclo]
    min-complexity = 12.0

  [linters-settings.maligned]
    suggest-new = true

  [linters-settings.goconst]
    min-len = 3.0
    min-occurrences = 3.0

  [linters-settings.misspell]
    locale = "US"

[linters]
  enable-all = true
  disable = [
    "golint", # deprecated
    "scopelint", # deprecated
    "interfacer", # deprecated
    "maligned", # deprecated
    "lll",
    "gas",
    "dupl",
    "prealloc",
    "gochecknoglobals",
    "gochecknoinits",
    "gomnd",
    "wsl",
    "nlreturn",
    "testpackage",
    "paralleltest",
    "tparallel",
    "goerr113",
    "wrapcheck",
    "exhaustive",
    "exhaustivestruct",
    "forbidigo",
  ]

[issues]
  exclude-use-default = false
  max-per-linter = 0
  max-same-issues = 0
  exclude = [
    "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked",
    "exported (type|method|function) (.+) should have comment or be unexported",
  ]
