version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - cyclop
    - dupl
    - err113
    - exhaustive
    - exhaustruct
    - gocognit
    - lll
    - mnd
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - paralleltest
    - prealloc
    - rowserrcheck
    - sqlclosecheck
    - testpackage
    - tparallel
    - varnamelen
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    depguard:
      rules:
        main:
          deny:
            - pkg: github.com/instana/testify
              desc: not allowed
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 23
    govet:
      enable:
        - shadow
    misspell:
      locale: US
    perfsprint:
      err-error: true
      errorf: true
      sprintf1: true
      strconcat: false
  exclusions:
    generated: lax
    rules:
      - linters:
          - funlen
        path: (.+)_test.go
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
