project_name: whoamiudp

builds:
  - binary: whoamiudp
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
      - arm64
    goarm:
      - '7'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^doc:'
      - '^chore:'
      - '^chore(deps):'
      - '^test:'
      - '^tests:'

archives:
  - id: whoamiudp
    name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm}}v{{ .Arm }}{{ end }}'
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE

docker_manifests:
  - name_template: 'traefik/whoamiudp:{{ .Tag }}'
    image_templates:
      - 'traefik/whoamiudp:{{ .Tag }}-amd64'
      - 'traefik/whoamiudp:{{ .Tag }}-arm64'
  - name_template: 'traefik/whoamiudp:latest'
    image_templates:
      - 'traefik/whoamiudp:{{ .Tag }}-amd64'
      - 'traefik/whoamiudp:{{ .Tag }}-arm64'
  - name_template: 'traefik/whoamiudp:v{{ .Major }}.{{ .Minor }}'
    image_templates:
      - 'traefik/whoamiudp:v{{ .Major }}.{{ .Minor }}-amd64'
      - 'traefik/whoamiudp:v{{ .Major }}.{{ .Minor }}-arm64'

dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'traefik/whoamiudp:latest-amd64'
      - 'traefik/whoamiudp:{{ .Tag }}-amd64'
      - 'traefik/whoamiudp:v{{ .Major }}.{{ .Minor }}-amd64'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.description=Tiny Go UDP server that prints OS information and request to output'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--platform=linux/amd64'

  - use: buildx
    goos: linux
    goarch: arm64
    dockerfile: buildx.Dockerfile
    image_templates:
      - 'traefik/whoamiudp:latest-arm64'
      - 'traefik/whoamiudp:{{ .Tag }}-arm64'
      - 'traefik/whoamiudp:v{{ .Major }}.{{ .Minor }}-arm64'
    build_flag_templates:
      - '--pull'
      - '--label=org.opencontainers.image.description=Tiny Go UDP server that prints OS information and request to output'
      - '--label=org.opencontainers.image.created={{.Date}}'
      - '--label=org.opencontainers.image.title={{.ProjectName}}'
      - '--label=org.opencontainers.image.revision={{.FullCommit}}'
      - '--label=org.opencontainers.image.version={{.Version}}'
      - '--label=org.opencontainers.image.source={{.GitURL}}'
      - '--platform=linux/arm64'
